/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a
random position.
Return the letter that was added to t.
Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
 */

import java.util.HashMap;
import java.util.Map;

public class DevByte54 {



    public char findTheDifference(String s, String t) {

        char extraCh = 0;

        Map<Character,Integer>  map =new HashMap<>();

        for( char c : s.toCharArray()){
            map.put(c, map.getOrDefault(c,0)+1);
        }


     for (int i =0;i < t.length();i++){

         char tCharacter = t.charAt(i);

         if (map.getOrDefault(tCharacter,0)==0){
                    extraCh=tCharacter;
                    break;
         } else{
                map.put(tCharacter,map.getOrDefault(tCharacter,0)-1);
         }
     }
       return extraCh;
     
    }

    public static void main(String[] args){


    }
}
